spring.application.name=springbootwebtutorial

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:h2:file:/Users/Test/Documents/SpringBootWebIntro/db
#spring.datasource.username=zayyni
#spring.datasource.password=zayyni123

